### ISSUE TITLE
Test example doesn't work - ImportError: No module named mptt

### ISSUE THREAD

**Issue by Pajinek** [hovel/imagestore#55]
$ python manage.py syncdb

Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pstudeni/Develop/Testing/imagestore/test/testproject/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/pstudeni/Develop/Testing/imagestore/test/testproject/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/pstudeni/Develop/Testing/imagestore/test/testproject/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pstudeni/Develop/Testing/imagestore/test/testproject/env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/pstudeni/Develop/Testing/imagestore/test/testproject/env/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named mptt

**Comment by lampslave** [comment]
Try to remove [this line](https://github.com/hovel/imagestore/blob/b0836d39dc1814f44a5db00c7719140b5201c558/test/testproject/testapp/settings.py#L120) or install django-mptt manually.
